version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ddmmaa/foodgram_backend
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media

  frontend:
    image: ddmmaa/foodgram_frontend
    env_file: ../.env
    depends_on:
      - backend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  gateway:
    image: ddmmaa/foodgram_gateway
    env_file: ../.env
    depends_on:
      - frontend
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/var/html/media