# Generated by Django 3.2.16 on 2024-04-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240416_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['recipe', 'ingredients'], 'verbose_name': 'Ингредиенты в рецепте', 'verbose_name_plural': 'ингредиенты в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_cart', 'ordering': ['user', 'recipe'], 'verbose_name': 'Корзина покупок', 'verbose_name_plural': 'корзина покупок'},
        ),
    ]
